### ISSUE TITLE
replaced alg?

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [someone1/gcp-jwt-go#5]
Hi Prateek,

How about a case that a JWS comes with altered alg with an unexpected algorithm? I don't understand code around this line.

https://github.com/someone1/gcp-jwt-go/blob/57304e1d70dbd56182f9cc97ac66da1979799b39/iam.go#L95

For examples, alg: 'none' and alg: 'HMAC-SHA*' must not be accepted. go-jose-v2 does not implement alg: 'none'.

**Comment by someone1** [comment]
The way it's supposed to work is you call [Override](https://github.com/someone1/gcp-jwt-go/blob/master/iam.go#L26) which replaces the [RS256 implementation of jwt-go](https://github.com/someone1/gcp-jwt-go/blob/master/iam_jwt.go#L22) so that when a header comes in with alg=RS256, it pulls `SigningMethodIAMJWT`. 

That line you linked to is doing an alg header check by ensuring that jwt-go picked an [instance of](https://github.com/someone1/gcp-jwt-go/blob/master/iam.go#L85) the correct signing method. It works since jwt-go would only pull the IAM signing method if it was registered to the alg found in the header of a JWT you're trying to parse. If alg= 'none' or 'HMAC-SHA*', jwt-go should not have pulled this signing method unless the developer incorrectly registered it to jwt-go for those algs.

I hope I was clear in my explanation, please let me know if I'm not.

**Comment by HIRANO-Satoshi** [comment]
I understood. I will go forward.

Thank you for explanation.
